server:
    port: 49999

spring:
  h2:
    console:
      enabled: true
      path: /h2
  # DataSource configuration
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/nak;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: