# Port for the webservice to operate on
server:
    port: 80

# BasicAuth configuration
security:
  basic:
    authorize-mode: authenticated
    realm: NAK Stundenplan Manager
  user:
    name: NAK
    password: TIMETABLE


spring:
  # H2 console configuration
  h2:
    console:
      enabled: true
      path: /h2
  # DataSource configuration
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/nak;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  # JPA configuration
  jpa:
    # Hibernate Specific properties
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
#      ddl-auto: create-drop
      use-new-id-generator-mappings: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false